// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4QcKCpwgJgWMvzd9VVbgYFMQzbQew8Bk',
    appId: '1:107032590733:web:058ba4742e6d33871ee5c4',
    messagingSenderId: '107032590733',
    projectId: 'fir-8e1c1',
    authDomain: 'fir-8e1c1.firebaseapp.com',
    storageBucket: 'fir-8e1c1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHda99jPRT2cvEyZqm2LvXbXFksSjo9ZM',
    appId: '1:107032590733:android:414a60a8a3103f321ee5c4',
    messagingSenderId: '107032590733',
    projectId: 'fir-8e1c1',
    storageBucket: 'fir-8e1c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5XJ4dmXbNqZCn6pKHLEULXub4QG2cAl8',
    appId: '1:107032590733:ios:9f6ed38b5c82d1b21ee5c4',
    messagingSenderId: '107032590733',
    projectId: 'fir-8e1c1',
    storageBucket: 'fir-8e1c1.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5XJ4dmXbNqZCn6pKHLEULXub4QG2cAl8',
    appId: '1:107032590733:ios:c3d3e3922c4a3ca01ee5c4',
    messagingSenderId: '107032590733',
    projectId: 'fir-8e1c1',
    storageBucket: 'fir-8e1c1.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
